### ISSUE TITLE
Bundler could not find compatible versions for gem "sprockets":

### ISSUE THREAD

**Issue by nitetrik** [katgironpe/simple-sinatra-mvc#1]
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets

    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets-helpers was resolved to 1.2.1, which depends on
        sprockets (>= 2.2)

    sprockets-memcache-store was resolved to 0.0.4, which depends on
      sprockets (~> 3.5.2)

    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets-sass was resolved to 0.1.0, which depends on
        sprockets (~> 2.0)
Bundler could not find compatible versions for gem "sprockets-helpers":
  In Gemfile:
    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets-helpers

    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets-helpers

    sinatra-asset-pipeline (~> 0.4) was resolved to 0.4.0, which depends on
      sprockets-sass was resolved to 0.4.0, which depends on
        sprockets-helpers (~> 0.1)

**Comment by katgironpe** [comment]
@nitetrik Thanks for reporting. It should be fixed now. Unfortunately we do not support Sprockets 3.x. Had to revert some changes for `sprockets-memcache-store`. That was causing the problem.
